# Generated by Django 5.2 on 2025-06-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_backup_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_user_backup",
                to="backend.server",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="active_endpoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_user",
                to="backend.endpoint",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="active_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_user",
                to="backend.server",
            ),
        ),
    ]
