# Generated by Django 5.2 on 2025-05-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_active_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="filter_date_from",
            field=models.DateField(blank=True, null=True, verbose_name="From"),
        ),
        migrations.AddField(
            model_name="user",
            name="filter_date_to",
            field=models.DateField(blank=True, null=True, verbose_name="To"),
        ),
    ]
