# Generated by Django 5.2 on 2025-05-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_filter_date_from_user_filter_date_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="plan",
            field=models.PositiveIntegerField(
                choices=[(0, "Free"), (1, "Pro")], default=0, verbose_name="Plan"
            ),
        ),
    ]
