# Generated by Django 5.2 on 2025-05-08 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0010_alter_server_group_alter_server_id_alter_server_logo_and_more",
        ),
        ("users", "0007_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_endpoint",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_user",
                to="backend.endpoint",
            ),
        ),
    ]
