# Generated by Django 5.2 on 2025-05-25 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_server_is_backup"),
        ("users", "0008_user_active_endpoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_backup_server",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_user_backup",
                to="backend.server",
            ),
        ),
    ]
