# Generated by Django 5.2 on 2025-06-10 07:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0019_alter_user_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titolo descrittivo della query", max_length=50
                    ),
                ),
                (
                    "code",
                    models.SlugField(
                        help_text="Codice univoco senza spazi (es. 'cpu_usage')",
                        unique=True,
                    ),
                ),
                (
                    "expression",
                    models.TextField(help_text="Espressione PromQL da eseguire"),
                ),
                (
                    "target_system",
                    models.CharField(
                        choices=[
                            ("prometheus", "Prometheus"),
                            ("uptime", "Uptime Kuma"),
                            ("restic", "Restic"),
                        ],
                        default="prometheus",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=256)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="entity_pictures/"
                    ),
                ),
                ("url", models.URLField()),
                ("check_keyword", models.CharField(blank=True, max_length=100)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(blank=True, max_length=256)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="entity_pictures/"
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=253,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Insert a valid domain",
                                regex="^(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}$",
                            )
                        ],
                    ),
                ),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=9100,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                ("is_backup", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
