# Generated by Django 5.2 on 2025-04-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='profile_picture',
            new_name='logo',
        ),
    ]
