# Generated by Django 5.2 on 2025-05-03 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_profile_picture_server_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='port',
            field=models.PositiveIntegerField(default=9100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)]),
        ),
        migrations.AddField(
            model_name='server',
            name='url',
            field=models.URLField(default='http://uptime.brainstorm.it'),
            preserve_default=False,
        ),
    ]
