# Generated by Django 5.2 on 2025-05-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_alter_server_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Titolo descrittivo della query", max_length=50
                    ),
                ),
                (
                    "codice",
                    models.SlugField(
                        help_text="Codice univoco senza spazi (es. 'cpu_usage')",
                        unique=True,
                    ),
                ),
                (
                    "expression",
                    models.TextField(help_text="Espressione PromQL da eseguire"),
                ),
                (
                    "qtype",
                    models.PositiveIntegerField(
                        choices=[(0, "Single"), (1, "Range")],
                        default=0,
                        verbose_name="QType",
                    ),
                ),
            ],
        ),
    ]
