# Generated by Django 5.2 on 2025-05-06 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_promquery"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promquery",
            old_name="codice",
            new_name="code",
        ),
    ]
