# Generated by Django 5.2 on 2025-05-07 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_rename_codice_promquery_code"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="server",
            name="url",
        ),
    ]
