# Generated by Django 5.2 on 2025-05-07 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_remove_server_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="domain",
            field=models.CharField(
                default="gitlab.brainstorm.it",
                max_length=253,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Insert a valid domain",
                        regex="^(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,}$",
                    )
                ],
            ),
            preserve_default=False,
        ),
    ]
