# Generated by Django 5.2 on 2025-05-08 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0019_alter_user_id"),
        ("backend", "0008_server_domain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servers",
                to="auth.group",
            ),
        ),
        migrations.AlterField(
            model_name="server",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
