# Generated by Django 5.2 on 2025-05-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "backend",
            "0010_alter_server_group_alter_server_id_alter_server_logo_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="promquery",
            name="qtype",
        ),
        migrations.AddField(
            model_name="promquery",
            name="target_system",
            field=models.CharField(
                choices=[
                    ("prometheus", "Prometheus"),
                    ("restic", "Restic"),
                    ("uptime", "Uptime Kuma"),
                ],
                default="prometheus",
                max_length=20,
            ),
        ),
    ]
