# Generated by Django 5.2 on 2025-05-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_remove_promquery_qtype_promquery_target_system"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promquery",
            name="target_system",
            field=models.CharField(
                choices=[
                    ("prometheus", "Prometheus"),
                    ("uptime", "Uptime Kuma"),
                    ("restic", "Restic"),
                ],
                default="prometheus",
                max_length=20,
            ),
        ),
    ]
