# Generated by Django 5.2 on 2025-05-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_alter_promquery_target_system"),
    ]

    operations = [
        migrations.AddField(
            model_name="server",
            name="is_backup",
            field=models.BooleanField(default=False),
        ),
    ]
